import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';


const roboto = Roboto({ subsets: ["latin"], weight: ['400','500','700'] });

export const metadata: Metadata = {
  title: "Cakes By Rayy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
           {children}
        </main>
        </body>
    </html>
  );
}
